services:
  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    container_name: 'rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: 'guest'
        RABBITMQ_DEFAULT_PASS: 'guest'
        RABBITMQ_DEFAULT_VHOST: '/'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq

networks:
  rabbitmq:
    driver: bridge
